# EmberlightWandere - offline compile check
#
# Compiles Assets/Scripts with Unity's bundled Roslyn WITHOUT launching the Unity editor.
# Purpose: verify a change still compiles while the editor is open (batchmode crashes then).
#
# Requires Library/UiReuseCompile.rsp (generated by Unity; lists all refs and source files).
# References that no longer exist on disk (removed third-party packages) are filtered out.
#
# Exit code: 0 = compiled; non-zero = compile errors, printed at the end.

[CmdletBinding()]
param(
    [string]$ProjectPath = (Split-Path -Parent $PSScriptRoot),
    [string]$OutDll = "Library/RefactorCheck/Emberlight.dll"
)

$ErrorActionPreference = 'Stop'

$csc = 'E:\Unity\Unity\2022.3.62f3\Editor\Data\DotNetSdkRoslyn\csc.dll'
if ($env:UNITY_EDITOR) {
    $candidate = Join-Path $env:UNITY_EDITOR 'Data\DotNetSdkRoslyn\csc.dll'
    if (Test-Path $candidate) { $csc = $candidate }
}
if (-not (Test-Path $csc)) { Write-Host "csc.dll not found: $csc"; exit 2 }

$dotnet = 'C:\Program Files\dotnet\dotnet.exe'
if (-not (Test-Path $dotnet)) { Write-Host 'dotnet runtime not found'; exit 2 }

$rspIn = Join-Path $ProjectPath 'Library\UiReuseCompile.rsp'
if (-not (Test-Path $rspIn)) { Write-Host "missing $rspIn - generate it once from Unity"; exit 2 }

$filteredDir = Join-Path $ProjectPath 'Library\RefactorCheck'
New-Item -ItemType Directory -Force -Path $filteredDir | Out-Null
$filtered = Join-Path $filteredDir 'compile.rsp'

$srcRoot = Join-Path $ProjectPath 'Assets\Scripts'
$sources = @(Get-ChildItem $srcRoot -Recurse -Filter *.cs | ForEach-Object {
    $_.FullName.Substring($ProjectPath.Length + 1).Replace('\', '/')
})

# Keep only options/defines/references; the source list is rediscovered so newly added or
# deleted files do not silently fall out of the check.
$dropped = 0
$kept = Get-Content $rspIn | Where-Object {
    if ($_ -match '^".*\.cs"$') { return $false }
    if ($_ -match '^-r:"?(.+?)"?$' -and -not (Test-Path $Matches[1])) { $dropped++; return $false }
    return $true
}

@($kept) + @($sources | ForEach-Object { '"' + $_ + '"' }) | Set-Content $filtered -Encoding ASCII

Write-Host "sources: $($sources.Count) file(s); filtered out $dropped unresolved reference(s)"

Push-Location $ProjectPath
try {
    $output = & $dotnet $csc "@$filtered" "-out:$OutDll" 2>&1
    $code = $LASTEXITCODE
} finally { Pop-Location }

$errors = @($output | Where-Object { "$_" -match ': error ' })
$warns = @($output | Where-Object { "$_" -match ': warning ' })

if ($code -eq 0) {
    Write-Host "COMPILE OK -> $OutDll ($($warns.Count) warning(s))"
    exit 0
}

Write-Host "COMPILE FAILED: $($errors.Count) error(s)"
$errors | Select-Object -First 60 | ForEach-Object { Write-Host "$_" }
exit $code
